.TH NAME 1
.\" NAME kwProcessXML, SECTION 1
.SH NAME
kwProcessXML \-
.SH SYNOPSIS
.B kwProcessXML
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR kwProcessXML
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
