.TH NAME 1
.\" NAME mkg3states, SECTION 1
.SH NAME
mkg3states \-
.SH SYNOPSIS
.B mkg3states
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR mkg3states
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
