.TH NAME 1
.\" NAME ProcessShader, SECTION 1
.SH NAME
ProcessShader \-
.SH SYNOPSIS
.B ProcessShader
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR ProcessShader
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
