.TH NAME 1
.\" NAME pvbatch, SECTION 1
.SH NAME
pvbatch \-
.SH SYNOPSIS
.B pvbatch
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR pvbatch
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
