.TH NAME 1
.\" NAME pvpython, SECTION 1
.SH NAME
pvpython \-
.SH SYNOPSIS
.B pvpython
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR pvpython
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
