.TH NAME 1
.\" NAME pvrenderserver, SECTION 1
.SH NAME
pvrenderserver \-
.SH SYNOPSIS
.B pvrenderserver
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR pvrenderserver
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
