.TH NAME 1
.\" NAME pvserver, SECTION 1
.SH NAME
pvserver \-
.SH SYNOPSIS
.B pvserver
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR pvserver
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
